<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="contact_us.aspx.cs" Inherits="prac8.contact_us" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="elementor-element elementor-element-53c16561 elementor-widget elementor-widget-heading" data-element_type="widget" data-id="53c16561" data-widget_type="heading.default" style="box-sizing: border-box; position: relative; width: 459.984px; margin-bottom: 20px; color: rgb(72, 79, 86); font-family: Lato__, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <div class="elementor-widget-container" style="box-sizing: border-box; transition: background 0.3s ease 0s, border 0.3s ease 0s, border-radius 0.3s ease 0s, box-shadow 0.3s ease 0s, -webkit-border-radius 0.3s ease 0s, -webkit-box-shadow 0.3s ease 0s;">
        <h3 class="elementor-heading-title elementor-size-default" style="box-sizing: border-box; margin: 0px; text-rendering: optimizespeed; word-break: break-word; font-family: var( --e-global-typography-primary-font-family ), Sans-serif; font-weight: var( --e-global-typography-primary-font-weight ); line-height: 1; color: var( --e-global-color-secondary ); font-size: var(--h3-font-size); padding: 0px;">Press Contact</h3>
    </div>
</div>
<div class="elementor-element elementor-element-3ccced2f u-links-anim-ul elementor-widget elementor-widget-text-editor" data-element_type="widget" data-id="3ccced2f" data-widget_type="text-editor.default" style="box-sizing: border-box; position: relative; color: var( --e-global-color-text ); font-family: var( --e-global-typography-text-font-family ), Sans-serif; font-weight: var( --e-global-typography-text-font-weight ); width: 459.984px; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <div class="elementor-widget-container" style="box-sizing: border-box; transition: background 0.3s ease 0s, border 0.3s ease 0s, border-radius 0.3s ease 0s, box-shadow 0.3s ease 0s, -webkit-border-radius 0.3s ease 0s, -webkit-box-shadow 0.3s ease 0s;">
        <div class="elementor-text-editor elementor-clearfix" style="box-sizing: border-box;">
            <p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1.25rem;">
                Bonkers Corner Marketing</p>
            <p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1.25rem;">
                Email:<span>&nbsp;</span><a href="mailto:info@bonkerscorner.com" style="box-sizing: border-box; color: var(--link-color); text-decoration: none; background-color: transparent; box-shadow: none; position: relative; display: inline-block;"><strong style="box-sizing: border-box; font-weight: 700;">info@bonkerscorner.com</strong></a></p>
            <p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1.25rem;">
                &nbsp;</p>
            <p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1.25rem;">
                <span style="color: rgb(122, 122, 122); font-family: Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Contact No. :<span>&nbsp;</span></span><strong style="box-sizing: border-box; font-weight: 700; color: rgb(122, 122, 122); font-family: Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">&nbsp;&nbsp;<a href="tel:02248906274" style="box-sizing: border-box; color: var(--link-color); text-decoration: none; background-color: transparent; box-shadow: none; position: relative; display: inline-block;">022 
                4890 6274</a><span>&nbsp;</span>/<span>&nbsp;</span><a href="tel:02248930015" style="box-sizing: border-box; color: var(--link-color); text-decoration: none; background-color: transparent; box-shadow: none; position: relative; display: inline-block;">022 4893 0015</a></strong><br style="box-sizing: border-box; color: rgb(122, 122, 122); font-family: Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
                <span style="color: rgb(122, 122, 122); font-family: Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Email:<span>&nbsp;</span></span><a href="mailto:info@bonkerscorner.com" style="box-sizing: border-box; color: var(--link-color); text-decoration: none; background-color: rgb(255, 255, 255); box-shadow: none; position: relative; display: inline-block; font-family: Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;"><strong style="box-sizing: border-box; font-weight: 700;">info@bonkerscorner.com</strong></a></p>
        </div>
    </div>
</div>
</asp:Content>
